// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var $$Array;

var Id;

var Int;

var List;

var Obj;

var Vector;

var Queue;

var $$String;

exports.$$Array = $$Array;
exports.Id = Id;
exports.Int = Int;
exports.List = List;
exports.Obj = Obj;
exports.Vector = Vector;
exports.Queue = Queue;
exports.$$String = $$String;
/* No side effect */
