// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Util = require("./util");
var $$String = require("bs-platform/lib/js/string.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function gets(prim) {
  return Util.gets(prim);
}

function solve(cheatSheet, n) {
  var lines = $$String.split_on_char(/* "\n" */10, $$String.trim(cheatSheet));
  return Belt_List.getBy(Belt_List.keepMap(lines, (function (l) {
                    var match = $$String.split_on_char(/* " " */32, l);
                    if (!match) {
                      return ;
                    }
                    var match$1 = match.tl;
                    if (match$1 && !match$1.tl) {
                      return Pervasives.int_of_string_opt(match$1.hd);
                    }
                    
                  })), (function (x) {
                return x > n;
              }));
}

function part2(param) {
  return Util.gets("https://oeis.org/A141481/b141481.txt").then(function (value) {
                var answer = solve(value, 312051);
                console.log(answer);
                return Promise.resolve(answer);
              }).catch(function (e) {
              console.log(e);
              return Promise.resolve(undefined);
            });
}

part2(undefined);

exports.gets = gets;
exports.solve = solve;
exports.part2 = part2;
/*  Not a pure module */
